# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsContext < Formula
  desc "AWS Context Switcher."
  homepage "https://github.com/mmxca/aws-context"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mmxca/aws-context/releases/download/v0.0.0/aws-context_0.0.0_darwin_arm64.tar.gz"
      sha256 "8970c8a74c90eb8d34085be0d422fe1cfe8bfccadadc5d24dac5695b493deb6d"

      def install
        bin.install "aws-context"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mmxca/aws-context/releases/download/v0.0.0/aws-context_0.0.0_darwin_amd64.tar.gz"
      sha256 "6e69a7521ac0aeebcbbd999628b16d4e9d05347c20b2ec7fdb390e482ef50385"

      def install
        bin.install "aws-context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mmxca/aws-context/releases/download/v0.0.0/aws-context_0.0.0_linux_amd64.tar.gz"
      sha256 "63c025d2f01a427320c2a34687f6f205edd5b776fd596b9b76cf9ddbfd60c17a"

      def install
        bin.install "aws-context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmxca/aws-context/releases/download/v0.0.0/aws-context_0.0.0_linux_arm64.tar.gz"
      sha256 "5b166958abd07941eb04869e8b9e15856490a2013bb174ca18df6c57f7a37785"

      def install
        bin.install "aws-context"
      end
    end
  end
end
