# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangHelloworld < Formula
  desc "Simple Hello World application."
  homepage "https://github.com/mmxca/golang-helloworld"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mmxca/golang-helloworld/releases/download/v0.0.3/golang-helloworld_0.0.3_darwin_arm64.tar.gz"
      sha256 "f6d8c318b7ece6f44b1c2da8b6d372c57952cf89a2cbe049e9b50da75666f030"

      def install
        bin.install "golang-helloworld"
        ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mmxca/golang-helloworld/releases/download/v0.0.3/golang-helloworld_0.0.3_darwin_amd64.tar.gz"
      sha256 "a35863d4406c5952821cff7caf717d3ffc9e0b81c4279e0e83afca79edf2b979"

      def install
        bin.install "golang-helloworld"
        ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmxca/golang-helloworld/releases/download/v0.0.3/golang-helloworld_0.0.3_linux_arm64.tar.gz"
      sha256 "e0404581be0212a2cd5e7f31f5b478e5313586839c0ce1ed12239d532190ba61"

      def install
        bin.install "golang-helloworld"
        ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mmxca/golang-helloworld/releases/download/v0.0.3/golang-helloworld_0.0.3_linux_amd64.tar.gz"
      sha256 "758803148144dc22f665481b306ff84d01b1b9b64f832dd247a9e0821d25654e"

      def install
        bin.install "golang-helloworld"
        ...
      end
    end
  end
end
